name: Hourly Follower Script

on:
  schedule:
    - cron: '0 * * * *' # تشغيل كل رأس ساعة
  workflow_dispatch:      # زر للتشغيل اليدوي

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install selenium webdriver-manager

      - name: Run Script
        run: python main.py
